version: "3.8"
services:
  rendezvous:
    build: .
    image: nt-backend-wrtc:local
    restart: unless-stopped
    environment:
      - HOST=0.0.0.0
      - PORT=1234                # important: matches ntcli default
      - ROOM_TTL=10m
      - HEARTBEAT=20s
      - HANDSHAKE_TIMEOUT=5m
      - MAX_PEERS_PER_ROOM=2
      - METRICS_ROUTE=/metrics
      - LOG_LEVEL=info
    ports:
      - "1234:1234"              # exposes http://127.0.0.1:1234 and ws://127.0.0.1:1234/ws
