version: "3.8"

services:
  nt-backend:
    build: .
    image: nt-backend-wrtc:local
    container_name: nt-backend
    restart: unless-stopped

    environment:
      # --- network ---
      - HOST=0.0.0.0
      - PORT=1234            # app HTTP port

      # --- rendezvous ---
      - ROOM_TTL=10m

      # --- websocket ---
      - WS_HEARTBEAT=20s
      - WS_HANDSHAKE=5m
      - WS_READ_BUFFER=65536
      - WS_WRITE_BUFFER=65536
      - WS_MAX_MSG=1048576
      - IDLE_TIMEOUT=0s

      # --- rate limits (0 disables) ---
      - WS_RATE_PER_MIN=0
      - HTTP_RATE_PER_MIN=0

      # --- TLS (optional) ---
      # - TLS_CERT_FILE=/certs/server.crt
      # - TLS_KEY_FILE=/certs/server.key

      # --- origin policy ---
      # - DEV=true                          # allow all origins
      # - CORS_ORIGINS=https://example.com  # prod allowlist

    # Internal-only visibility for other containers (nginx, prometheus, etc.)
    expose:
      - "8080"   # app HTTP

    networks:
      web:
        aliases: [nt-backend]
      observability:
        aliases: [nt-backend]

    # NOTE: removed healthcheck — distroless has no shell/curl.
    # If you really need one, add a tiny probe binary in your image
    # and use ["CMD", "/probe", "--addr=127.0.0.1:1234"] or similar.

networks:
  web:
    external: true
    name: whitenoise_web
  observability:
    external: true
    name: whitenoise_observability
